/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void rollReturnsArray() {
        Library library = new Library();
        int[] returnedArray;
        returnedArray = library.roll(5);
        assertEquals(new int[5], returnedArray);
    }

    @Test void duplicatesReturnsTrue() {
        Library library = new Library();
        int[] array ={1,2,3,3,4,5};
        assertTrue(library.containsDuplicates(array));
    }

    @Test void aveReturnsFloat() {
        Library library = new Library();
        int[] array= {1,2,3,4,5};
        float returnedFloat = library.averages(array);
        assertEquals(3.0f, returnedFloat);
    }

    @Test void lowestArrayReturned() {
        Library library = new Library();
        int[][] array = {{1,2,3},{2,4,7},{3,6,9}};
        int[] returnedArray = library.lowestArrayAve(array);
        assertEquals(new int[]{1,2,3}, returnedArray);
    }

}
