/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n) {
        Random rand = new Random();
        int[] array = new int[n];
        for (int i = 0; i <= n; i++){
            int result = rand.nextInt(6)+1;
            array[i] = result;
        }
        return array;
    }

    public static boolean containsDuplicates(int[] array){
        boolean hasDuplicates = false;
        for (int i = 0; i < array.length; i++){
          for (int j = i + 1; j < array.length; j++){
              if (array[i] == array[j]){
                  hasDuplicates = true;
                  break;
              }
          }
       }
       return hasDuplicates;
    }

    public static float averages(int[]array){
        int acc = 0;
        for (int i = 0; i < array.length; i++) {
          acc= acc + array[i];
        }
        float ave = (float)acc / (float)array.length;
        return ave;
    }

    public static int[] arrays(){

    }
}
