/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {
    String name;
    float stars;
    String category;

    ArrayList<Review> totalReviews = new ArrayList<>();

    public Restaurant(String name, String category) {
        this.name = name;
        this.category = category;
    }


    public String toString() {
        return "Restaurant\nname= " + name +
                "\nstars= " + stars +
                "\ncategory= " + category;
    }

    public void addReviewUpdateStars(Review review) {
        if(review instanceof TheaterReview){
            throw new IllegalArgumentException("Theater review is not allowed");
        }

        totalReviews.add(review);
        float acc = 0;
        for (Review r:totalReviews) {
            acc = (float)r.getRating() + acc;
        }
        stars = acc/totalReviews.size();
    }
}
