/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {
    String name;
    int stars;
    String category;

    ArrayList<Integer> totalRatings = new ArrayList<>();

    public Restaurant(String name, int stars, String category) {
        this. name = name;
        this.stars = stars;
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getStars() {
        return stars;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
    }

    public void addReview(int rating) {
        totalRatings.add(rating);
        int acc = 0;
        for (int r:totalRatings) {
            acc = r + acc;
        }
        stars = acc/totalRatings.size();
    }
}
